version: '3.7'
services:
  web:
    build: web
    restart: always
    ports:
      - 5000:5000
    environment:
      - DEBUG=0
    networks:
      - flask_network

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - flask_network

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - flask_network

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appnoo
    volumes:
      - postgres_data1:/var/lib/postgresql/data

networks:
  flask_network:

volumes:
  postgres_data1:
